name: "Release -- NPM"
on:
  push:
    tags:
      - "npmmethod*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@codspace'

      - name: "Generate tgz and publish to NPM"
        uses: ./.github/devcontainers-action # TODO: Once 'devcontainers/action' is published, use that.
        with:
          publish-features: "true"
          publish-to-npm: "true" # EXPERIMENTAL!
          base-path-to-features: "./src"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CREDENTIAL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get or Create Release at current tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Lets us upload our own artifact from previous step
          artifactErrorsFailBuild: true
          artifacts: "./*.tgz,devcontainer-collection.json"
          token: ${{ secrets.GITHUB_TOKEN }}
